add support for nested index routes (fixes #281)
fastify/fastify-cors pull request #282
Opened 2023-12-09 00:35 UTC by GlenTiki

Fixes #281. I'll comment on code to clarify reasoning.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-12-09 00:42 UTC, GlenTiki commented on index.js
> +  if (fastify.prefix) { fastify.options('/', handlerOptions, handler) }
without doing this if check existing tests break - this literally just fixes the case for the test I added.

I think on root index routes, fastify applies `/*` to the index route, but on prefixed routes, it doesn't?

2023-12-10 13:28 UTC, mcollina approved these changes
lgtm

2023-12-12 20:58 UTC, Uzlopak requested changes
I am not at my PC but reading this i think the solution is wrong in case fastify.prefix is set. I mean, yes the test passes but because only this one case was patched. 

I assume that you need to do 
```js
fastify.options(fastify.prefix + '*', handlerOptions, handler)
```
To fix it properly.

Blocking the merging.

2023-12-12 23:56 UTC, GlenTiki commented
@Uzlopak when you’re back at a desk can you take a look again and give further guidance on how to fix this? I tried some variations on your suggestion, but that fails the added test case.

2023-12-13 00:20 UTC, Uzlopak reviewed
I reviewed this again.

Yes, your assumption regarding index seems to be right. But it feels like this is an error in upstream, either find-my-way or fastify itself. 

So unfortunately I can not give you more hints. 

Something is odd. Well this is my gut feeling. 

@mcollina 
@ivan-tymoshenko

@GlenTiki wrote;
> I think on root index routes, fastify applies /* to the index route, but on prefixed routes, it doesn't?


Can this be a bug in upstream?

2023-12-13 11:08 UTC, ivan-tymoshenko commented
It looks like a bug in fastify for me.

2023-12-14 17:09 UTC, GlenTiki commented
I tested fastify with some simple tests which are passing (attached below). Meaning the issue lies in this repo.

I'm now digging in to see if the error lies in the hook this repo adds, but, given this solves the test case, it's an alternate valid solution 😅 

<details>
<summary>Expand to see test</summary>

```js
'use strict'

const t = require('tap')
const test = t.test
const Fastify = require('fastify')

test('Routing to the wildcard route works the same for prefixed or root route', async t => {
    t.plan(3)

    const fastify = Fastify()

    const handler = async (req, reply) => {
        return { custom: "body" }
    }

    fastify.route({ method: 'OPTIONS', url: '/*', handler })
    fastify.register(async (scope, opts) => {
        scope.route({ method: 'OPTIONS', url: '/*', handler })
    }, { prefix: '/prefix' })

    await fastify.ready()

    const result = (await fastify.inject({ method: "OPTIONS", path: '/' })).payload

    t.equal(result, JSON.stringify({ custom: "body" }))
    t.equal(result, (await fastify.inject({ method: "OPTIONS", path: '/prefix' })).payload)
    t.equal(result, (await fastify.inject({ method: "OPTIONS", path: '/prefix/' })).payload)
})


test('Routing to the wildcard route works the same for nested prefixed or root route', async t => {
    t.plan(3)

    const fastify = Fastify()

    const handler = async (req, reply) => {
        return { custom: "body" }
    }

    const nestedWildcardPlugin = async (scope, opts) => {
        scope.route({ method: 'OPTIONS', url: '/*', handler })
    }

    fastify.register(nestedWildcardPlugin)
    fastify.register(async (scope, opts) => {
        scope.register(nestedWildcardPlugin)
    }, { prefix: '/prefix' })

    await fastify.ready()

    const result = (await fastify.inject({ method: "OPTIONS", path: '/' })).payload

    t.equal(result, JSON.stringify({ custom: "body" }))
    t.equal(result, (await fastify.inject({ method: "OPTIONS", path: '/prefix' })).payload)
    t.equal(result, (await fastify.inject({ method: "OPTIONS", path: '/prefix/' })).payload)
})

```

</details>

2023-12-15 07:11 UTC, climba03003 requested changes
You should be using the similar approach for 404 catcher in `fastify`.
https://github.com/fastify/fastify/blob/af8bd46a7b1d18c68558f07e020180f5e86922b5/lib/fourOhFour.js#L160-L161C11

2023-12-15 07:38 UTC, Uzlopak commented
@climba03003 

I tested that and it didnt work. Can you provide a suggestion to fix this issue?

2023-12-16 16:37 UTC, climba03003 commented
I would like to revert https://github.com/fastify/fastify-cors/pull/278 after some investigation.
We cannot replace `*` with `/*` directly without sacrifice the ability to to replace response for `options` route.

We need another approach to fix the issue mentioned inside #278

2023-12-17 09:39 UTC, Fdawgs commented
> I would like to revert https://github.com/fastify/fastify-cors/pull/278 after some investigation.
> 
> We cannot replace `*` with `/*` directly without sacrifice the ability to to replace response for `options` route.
> 
> 
> 
> We need another approach to fix the issue mentioned inside #278

Sounds good!

2023-12-17 11:49 UTC, mcollina commented
@climba03003 can you open a PR and add a test to prevent the regression in the future?

2023-12-18 11:59 UTC, closed without merging